name: Update Anytype-ts

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update scoop manifest
        run: |
          cd bucket
          latest_version=$(curl --silent "https://api.github.com/repos/anyproto/anytype-ts/releases/latest" | jq -r .tag_name)
          url=$(curl --silent "https://api.github.com/repos/anyproto/anytype-ts/releases/latest" | jq -r '.assets[] | select(.name | endswith(".exe")) | .browser_download_url')
          curl -L -o anytype-ts.exe "$url"
          checksum=$(sha256sum anytype-ts.exe | cut -d ' ' -f 1)
          cat > anytype-ts.json <<EOL
          {
            "version": "${latest_version}",
            "architecture": {
              "64bit": {
                  "url": "${url}",
                  "hash": "d8ce393fafe2e3397499b605fb078d8f3d5ff8d7886a944ac61dd41d9c058adb",
                  "pre_install": [
                      "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app*.7z\" \"$dir\"",
                      "Remove-Item \"$dir\\`$R0\", \"$dir\\`$PLUGINSDIR\" -Force -Recurse"
                  ]
              }
            },
            "bin": "Anytype.exe",
            "shortcuts": [
              [
                  "Anytype.exe",
                  "Anytype"
              ]
            ]
          }
          EOL

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update json
          file_pattern: '*.json'
